#Controller to continuously publish joint states/positions 
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

#Controller to control robot arm joints
robot_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint1:
      trajectory: 0.1
      goal: 0.1
    joint2:
      trajectory: 0.1
      goal: 0.1
    joint3:
      trajectory: 0.1
      goal: 0.1
    joint4:
      trajectory: 0.1
      goal: 0.1
    
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  gains:
    joint_1: {p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0}
    joint_2: {p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0}
    joint_3: {p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0}
    joint_4: {p: 100.0, d: 1.0, i: 1.0, i_clamp: 1.0}

#Controller to control end effector joints
end_effector_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_5
    - joint_6

  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    joint_5:
      trajectory: 0.1
      goal: 0.1
    joint_6:
      trajectory: 0.1
      goal: 0.1

    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10

  gains:
    joint_5: {p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0}
    joint_6: {p: 10.0, d: 1.0, i: 1.0, i_clamp: 1.0}