controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_5
      - joint_6
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: idle
  - group: gripper_group
    pose: open_gripper